global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.ComponentModel.DataAnnotations;
global using InventoryManagementSystemDAL.Entity;
global using InventoryManagementSystemDAL.Repo;
global using InventoryManagementSystemDAL.DBContext;